In [85]:
import pandas as pd

df = pd.read_excel(r"C:\Users\Ryan Wong\Desktop\Beach Water Quality Cleaned.xlsx")

df

,Beach Name,Measurement Timestamp,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life,Date,Time,Month,Year
0,Calumet Beach,04/07/2018 12:30:00 AM,21.7,3.15,NaN,0.389,3.0,0.0,2018-04-07,12:30:00 AM,4,2018
1,Ohio Street Beach,06/14/2019 07:00:00 PM,16.0,2.18,NaN,0.137,3.0,11.8,2019-06-14,07:00:00 PM,6,2019
2,Ohio Street Beach,05/16/2018 01:00:00 PM,21.7,1.92,NaN,0.023,1.0,10.3,2018-05-16,01:00:00 PM,5,2018
3,Ohio Street Beach,05/16/2018 02:00:00 PM,21.9,1.81,NaN,0.026,6.0,10.3,2018-05-16,02:00:00 PM,5,2018
4,Ohio Street Beach,06/04/2018 09:00:00 AM,23.0,0.03,NaN,0.021,8.0,12.4,2018-06-04,09:00:00 AM,6,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
45851,Ohio Street Beach,09/17/2024 09:00:00 PM,22.9,0.59,NaN,0.000,6.2,11.7,2024-09-17,09:00:00 PM,9,2024
45852,Ohio Street Beach,09/17/2024 10:00:00 PM,22.4,0.88,NaN,0.000,6.4,11.8,2024-09-17,10:00:00 PM,9,2024
45853,Ohio Street Beach,09/17/2024 11:00:00 PM,21.9,0.60,NaN,0.000,6.4,12.3,2024-09-17,11:00:00 PM,9,2024
45854,Ohio Street Beach,09/18/2024 12:00:00 AM,21.4,0.80,NaN,0.000,6.4,11.6,2024-09-18,12:00:00 AM,9,2024
45855,Ohio Street Beach,09/18/2024 01:00:00 AM,21.1,0.56,NaN,0.000,6.5,10.8,2024-09-18,01:00:00 AM,9,2024

In [86]:
#QUESTIONS FOR ANALYSIS:

#Do certain beaches have higher averages of measurements than others?
#How do the different months/seasons vary in terms of measurements than others? What about time of day? And years?
#What is the correlation to battery life to time of day/month or beach location?
#What is the correlation to water temperature and turbidity to wave height and wave period?

#Are there any extreme outliers in distribution of this dataset?
#How frequently is each beach measured?


df.info()
#Turbidity = How clear the water is. How many particles are affecting water transparency. The higher the turbidity, the more foggy the water is
#Wave Period = Wave frequency. The lower the number, the closer the distance between waves (more choppy water conditions). Higher indicates wider distance between waves (more calm water conditions)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45856 entries, 0 to 45855
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Beach Name             45856 non-null  object
 1   Measurement Timestamp  45856 non-null  object
 2   Water Temperature      43702 non-null  float64
 3   Turbidity              43702 non-null  float64
 4   Transducer Depth       10034 non-null  float64
 5   Wave Height            44592 non-null  float64
 6   Wave Period            44592 non-null  float64
 7   Battery Life           45470 non-null  float64
 8   Date                   45856 non-null  datetime64[ns]
 9   Time                   45856 non-null  object
 10  Month                  45856 non-null  int64
 11  Year                   45856 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(2), object(3)
memory usage: 4.2+ MB

In [87]:
df.describe()
#FINDINGS:
#near equal amount of data for Water Temp, Turbidity, Wave Height, Wave Period, and Battery Life
#only 1/4th of data available for Transducer Depth, most values NaN
#Turbidity max value (1683.48) abormally high compared to 50th (1.35) and 75th (2.94) percentile

,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life,Month,Year
count,43702.000000,43702.000000,10034.000000,44592.000000,44592.000000,45470.000000,45856.000000,45856.000000
mean,19.691584,5.904444,1.570235,0.168741,3.867878,11.256213,7.143405,2016.540060
std,3.413810,31.914919,0.175118,0.091644,1.560330,0.957063,1.127379,2.974608
min,0.000000,0.000000,-0.082000,0.000000,1.000000,0.000000,4.000000,2013.000000
25%,17.300000,0.740000,1.426000,0.107000,3.000000,10.700000,6.000000,2015.000000
50%,20.000000,1.350000,1.578000,0.151000,3.000000,11.200000,7.000000,2015.000000
75%,22.500000,2.940000,1.721000,0.201000,4.000000,11.700000,8.000000,2017.000000
max,37.300000,1683.480000,2.214000,1.467000,10.000000,14.800000,10.000000,2024.000000

In [88]:
df.isnull().sum()

Beach Name                   0
Measurement Timestamp        0
Water Temperature         2154
Turbidity                 2154
Transducer Depth         35822
Wave Height               1264
Wave Period               1264
Battery Life               386
Date                         0
Time                         0
Month                        0
Year                         0
dtype: int64

In [89]:
df.nunique()

Beach Name                   8
Measurement Timestamp    21734
Water Temperature          211
Turbidity                 3683
Transducer Depth           775
Wave Height                629
Wave Period                 70
Battery Life               102
Date                       973
Time                        30
Month                        7
Year                        11
dtype: int64

In [90]:
#Do certain beaches have higher averages of measurements than others?

df.groupby('Beach Name').mean().sort_values(by='Water Temperature', ascending=False)

,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life,Month,Year
Beach Name,,,,,,,,
Ohio Street Beach,20.623662,8.964216,1.735757,0.156343,3.685255,11.545114,7.197949,2018.559767
Calumet Beach,20.373104,1.886594,1.449376,0.152585,3.532365,10.972391,7.207001,2015.042801
Rainbow Beach,18.741250,3.164116,1.553982,0.203868,4.278459,11.198938,7.305429,2014.716712
Montrose Beach,18.640534,2.898791,1.638710,0.202249,4.330627,11.078729,7.034673,2015.040864
63rd Street Beach,18.459901,4.313150,1.753354,0.155694,4.205527,10.774788,6.925124,2014.660135
Osterman Beach,17.933615,8.707598,1.358719,0.184694,4.003232,11.138339,6.993536,2014.549975
New Site,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,2023.000000
Ohio Street Beach Buoy,NaN,NaN,NaN,NaN,NaN,NaN,7.372603,2023.000000

In [91]:
#How do the different months/seasons vary in terms of measurements than others? What about time of day? And years?

#month/season:
df.groupby('Month')[['Water Temperature', 'Turbidity', 'Transducer Depth', 'Wave Height', 'Wave Period', 'Battery Life']].mean()

,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life
Month,,,,,,
4,21.700000,3.150000,NaN,0.389000,3.000000,0.000000
5,14.751655,10.579902,1.456138,0.174384,3.808161,11.802875
6,17.542685,4.608764,1.534947,0.169373,3.729001,11.186012
7,20.298675,3.974617,1.587278,0.168488,3.930660,11.312377
8,22.004947,8.545174,1.594937,0.170761,3.832794,11.134358
9,20.235338,4.953000,1.630908,0.170799,4.059047,11.217169
10,15.757143,71.691429,NaN,0.020299,5.156793,12.102933

In [92]:
#time of day:
df.groupby('Time')[['Water Temperature', 'Turbidity', 'Transducer Depth', 'Wave Height', 'Wave Period', 'Battery Life']].mean()

,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life
Time,,,,,,
01:00:00 AM,19.516370,6.560558,1.568434,0.161573,4.269039,11.243871
01:00:00 PM,20.052035,5.489886,1.578500,0.175548,3.623486,11.297602
02:00:00 AM,19.378664,5.452269,1.576500,0.158897,4.213875,11.228254
02:00:00 PM,20.244824,6.506179,1.578251,0.179186,3.585874,11.306136
02:20:00 PM,NaN,NaN,NaN,NaN,NaN,NaN
03:00:00 AM,19.270797,6.063111,1.574065,0.158611,3.973526,11.219653
03:00:00 PM,20.339601,6.013454,1.573862,0.181571,3.649921,11.297777
03:20:00 PM,NaN,NaN,NaN,NaN,NaN,NaN
03:30:00 PM,NaN,NaN,NaN,NaN,NaN,NaN
04:00:00 AM,19.235359,5.239785,1.572876,0.156743,3.961526,11.182714
04:00:00 PM,20.346821,5.343093,1.573160,0.184561,3.756721,11.293737
04:20:00 PM,NaN,NaN,NaN,NaN,NaN,NaN
05:00:00 AM,19.173911,6.037286,1.561788,0.154669,4.126042,11.200531
05:00:00 PM,20.350540,5.400346,1.569376,0.184956,3.690021,11.284516
06:00:00 AM,19.113551,5.790221,1.568598,0.154461,4.168896,11.216365
06:00:00 PM,20.243686,5.118222,1.564151,0.184253,3.878120,11.285357
07:00:00 AM,19.113732,5.957220,1.563266,0.154047,4.184248,11.249574
07:00:00 PM,20.081212,7.591012,1.559521,0.183470,3.796739,11.271703
08:00:00 AM,19.133534,5.740312,1.571408,0.156568,3.965648,11.265825
08:00:00 PM,19.965293,5.147392,1.560359,0.180410,3.724030,11.263092
09:00:00 AM,19.267788,6.082548,1.565838,0.158137,3.808689,11.263328
09:00:00 PM,19.871118,5.604110,1.565160,0.174654,3.659265,11.249166
10:00:00 AM,19.430256,5.912253,1.569529,0.161030,3.731737,11.265099
10:00:00 PM,19.726134,6.537408,1.567389,0.172829,3.771224,11.237241
11:00:00 AM,19.639054,5.840655,1.583584,0.167499,3.653681,11.262427
11:00:00 PM,19.662255,6.546547,1.568705,0.168006,3.929754,11.242282
11:30:00 AM,22.700000,0.000000,NaN,0.015000,6.000000,12.800000
12:00:00 AM,19.543211,6.432644,1.580493,0.163164,4.147283,11.234546
12:00:00 PM,19.801583,5.382560,1.570220,0.172047,3.626017,11.286523
12:30:00 AM,21.700000,3.150000,NaN,0.389000,3.000000,0.000000

In [93]:
#years:
df.groupby('Year')[['Water Temperature', 'Turbidity', 'Transducer Depth', 'Wave Height', 'Wave Period', 'Battery Life']].mean()

,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life
Year,,,,,,
2013,21.160000,4.170000,1.237200,0.173200,4.800000,9.720000
2014,19.079105,8.271432,1.570401,0.165053,3.863994,10.987705
2015,18.595251,4.388865,NaN,0.171838,4.025695,11.076138
2016,20.947967,1.818600,NaN,0.182710,3.875678,11.003894
2017,20.055380,2.508552,NaN,0.187000,3.000000,11.127119
2018,21.371011,1.799277,NaN,0.178454,3.856850,11.048794
2019,19.803458,2.420350,NaN,0.168164,3.995390,11.086016
2020,23.810855,1.170263,NaN,0.131726,3.860335,11.520724
2021,20.729626,13.575326,NaN,0.223154,4.269519,11.547807
2023,NaN,NaN,NaN,0.133636,4.054638,12.768382
2024,21.586172,22.296463,NaN,0.116706,3.619391,13.044018

In [94]:
#What is the correlation to battery life to time of day/month?
#what about to beach location?

df.groupby('Time')[['Battery Life']].mean().sort_values(by='Battery Life')

             Battery Life
Time
12:30:00 AM      0.000000
04:00:00 AM     11.182714
05:00:00 AM     11.200531
06:00:00 AM     11.216365
03:00:00 AM     11.219653
02:00:00 AM     11.228254
12:00:00 AM     11.234546
10:00:00 PM     11.237241
11:00:00 PM     11.242282
01:00:00 AM     11.243871
09:00:00 PM     11.249166
07:00:00 AM     11.249574
11:00:00 AM     11.262427
08:00:00 PM     11.263092
09:00:00 AM     11.263328
10:00:00 AM     11.265099
08:00:00 AM     11.265825
07:00:00 PM     11.271703
05:00:00 PM     11.284516
06:00:00 PM     11.285357
12:00:00 PM     11.286523
04:00:00 PM     11.293737
01:00:00 PM     11.297602
03:00:00 PM     11.297777
02:00:00 PM     11.306136
11:30:00 AM     12.800000
02:20:00 PM           NaN
03:20:00 PM           NaN
03:30:00 PM           NaN
04:20:00 PM           NaN

In [95]:
#df.groupby('Month')[['Battery Life']].mean().sort_values(by='Battery Life')
df.groupby('Month').mean().sort_values(by='Battery Life')

,Water Temperature,Turbidity,Transducer Depth,Wave Height,Wave Period,Battery Life,Year
Month,,,,,,,
4,21.700000,3.150000,NaN,0.389000,3.000000,0.000000,2018.000000
8,22.004947,8.545174,1.594937,0.170761,3.832794,11.134358,2016.545929
6,17.542685,4.608764,1.534947,0.169373,3.729001,11.186012,2016.065175
9,20.235338,4.953000,1.630908,0.170799,4.059047,11.217169,2017.381037
7,20.298675,3.974617,1.587278,0.168488,3.930660,11.312377,2016.148798
5,14.751655,10.579902,1.456138,0.174384,3.808161,11.802875,2017.991395
10,15.757143,71.691429,NaN,0.020299,5.156793,12.102933,2022.850667

In [96]:
df.groupby('Beach Name')[['Battery Life']].mean().sort_values(by='Battery Life')

                        Battery Life
Beach Name
63rd Street Beach          10.774788
Calumet Beach              10.972391
Montrose Beach             11.078729
Osterman Beach             11.138339
Rainbow Beach              11.198938
Ohio Street Beach          11.545114
New Site                         NaN
Ohio Street Beach Buoy           NaN

In [97]:
#What is the correlation to water temperature and turbidity to wave height and wave period?

#Wave Period to Water Temperature
with pd.option_context('display.max_rows', None): #<-- display all rows instead of first and last 5
    print(df.groupby('Wave Period')[['Water Temperature']].mean().sort_values(by='Water Temperature'))

             Water Temperature
Wave Period
1.2                  16.400000
9.0                  18.494718
8.0                  18.818588
7.0                  18.941121
6.0                  19.027604
10.0                 19.141837
5.0                  19.150168
5.4                  19.184615
4.0                  19.198852
4.9                  19.625000
4.4                  19.864407
3.0                  19.870870
2.0                  20.073043
4.7                  20.303846
4.3                  20.364912
1.7                  20.602000
1.5                  20.631579
3.2                  20.647368
4.6                  20.665625
3.8                  20.745000
6.7                  20.914286
1.0                  20.950000
3.6                  20.978571
1.6                  21.057377
2.7                  21.089011
5.8                  21.112500
2.2                  21.182270
2.6                  21.236522
2.5                  21.244715
4.8                  21.251429
2.1                  21.272093
1.8                  21.273214
4.5                  21.273239
1.9                  21.294186
7.7                  21.300000
2.4                  21.346457
6.9                  21.444444
7.6                  21.500000
7.5                  21.500000
3.3                  21.508108
5.7                  21.538462
2.8                  21.543590
3.7                  21.563636
4.1                  21.673333
3.1                  21.709804
2.3                  21.710949
1.4                  21.717647
5.3                  21.807692
6.6                  21.891429
2.9                  22.009524
6.8                  22.033333
1.3                  22.050000
4.2                  22.069767
7.2                  22.100000
7.1                  22.100000
3.5                  22.134146
5.6                  22.220000
5.2                  22.400000
3.4                  22.432500
5.1                  22.644000
3.9                  22.680769
7.4                  22.683333
6.2                  22.731481
6.5                  22.922330
5.5                  23.000000
6.1                  23.063636
6.4                  23.209804
6.3                  23.476543
7.3                  23.750000
5.9                  24.223810

In [98]:
#Wave Period to Turbidity
with pd.option_context('display.max_rows', None):
    print(df.groupby('Wave Period')[['Turbidity']].mean().sort_values(by='Turbidity'))

             Turbidity
Wave Period
1.0           1.814833
10.0          1.947415
9.0           2.206849
2.0           2.470148
3.0           3.607448
6.4           3.750915
5.8           4.756250
5.0           5.008290
4.0           5.089782
6.1           5.523182
5.7           5.658462
6.5           5.861845
6.3           6.643827
6.2           6.662963
6.0           7.457454
7.3           7.890000
5.9           8.639524
7.0           9.809581
5.6          11.047000
6.6          11.209429
8.0          11.527565
5.4          14.393077
5.3          14.672308
5.2          16.043333
4.5          16.171972
4.2          16.245465
4.4          16.511864
1.3          16.630000
5.1          17.370800
3.1          17.545686
7.4          17.591667
7.2          17.855556
4.7          18.016923
4.6          18.722344
3.7          19.286364
3.5          19.289756
3.9          19.423846
4.3          19.507368
7.1          19.950000
6.8          19.968000
4.1          20.598000
1.2          20.966667
4.8          21.045143
3.4          21.850000
4.9          22.067000
1.8          23.372321
2.9          24.323095
7.6          24.540000
3.2          26.254474
6.7          26.407143
1.5          26.995526
7.7          27.160000
3.6          27.336250
3.3          27.409730
1.7          28.065200
2.1          28.155194
2.4          28.716535
6.9          28.802222
2.3          28.895182
2.7          28.921868
2.8          29.537436
1.9          29.644070
1.6          30.080656
1.4          30.292941
2.2          30.315390
5.5          30.734000
2.6          33.305652
7.5          35.340000
2.5          35.842195
3.8          35.984250

In [99]:
#Wave Height to Water Temperature
with pd.option_context('display.max_rows', None):
    print(df.groupby('Wave Height')[['Water Temperature']].mean().sort_values(by='Water Temperature'))

             Water Temperature
Wave Height
0.583                 0.000000
0.576                 0.000000
0.575                 0.000000
0.545                 0.000000
0.544                 5.600000
0.557                 7.933333
0.405                 9.125000
0.548                 9.700000
0.625                 9.800000
0.598                 9.900000
0.561                10.060000
0.606                10.625000
0.537                10.633333
0.611                11.300000
0.509                11.620000
0.549                11.700000
0.508                11.750000
0.591                11.900000
0.527                11.950000
0.660                12.200000
0.541                12.200000
0.535                12.220000
0.637                12.400000
0.543                12.400000
0.628                12.500000
0.442                12.500000
0.626                12.600000
0.644                12.900000
0.698                13.000000
0.562                13.125000
0.523                13.150000
0.498                13.166667
0.632                13.200000
0.655                13.300000
0.584                13.340000
0.594                13.400000
0.554                13.433333
0.597                13.500000
0.613                13.600000
0.519                13.800000
0.518                13.900000
0.612                14.200000
0.415                14.216667
0.563                14.400000
0.602                14.400000
0.615                14.500000
0.471                14.575000
1.229                14.600000
0.528                14.600000
0.546                14.700000
0.552                14.733333
0.592                14.850000
0.491                14.860000
0.475                14.900000
0.608                15.100000
0.526                15.120000
0.461                15.200000
0.449                15.322222
0.522                15.350000
0.484                15.400000
0.501                15.480000
0.511                15.500000
0.532                15.520000
0.589                15.550000
0.551                15.566667
0.447                15.625000
0.640                15.700000
0.555                15.750000
0.419                15.771429
0.516                15.816667
0.629                15.850000
0.514                15.866667
0.571                15.950000
0.459                15.975000
0.601                16.000000
0.493                16.125000
0.538                16.166667
0.599                16.200000
0.521                16.200000
0.607                16.200000
0.452                16.225000
0.530                16.230000
0.436                16.262500
0.445                16.300000
0.536                16.300000
0.045                16.300000
0.515                16.325000
0.412                16.400000
0.462                16.466667
0.595                16.500000
0.438                16.500000
0.391                16.566667
0.502                16.600000
0.492                16.683333
0.510                16.685714
0.467                16.750000
0.485                16.766667
0.396                16.775000
0.455                16.788889
0.604                16.800000
0.487                16.800000
0.416                16.841667
0.567                16.866667
0.504                16.875000
0.559                17.000000
0.481                17.050000
0.533                17.060000
1.117                17.100000
1.467                17.100000
0.381                17.142857
0.558                17.180000
0.486                17.200000
0.474                17.280000
0.556                17.300000
0.658                17.300000
0.406                17.323529
0.507                17.400000
0.393                17.431250
0.394                17.433333
0.456                17.460000
0.384                17.464286
0.463                17.500000
0.496                17.500000
0.465                17.500000
0.494                17.533333
0.344                17.539130
0.570                17.550000
0.574                17.566667
0.446                17.583333
0.605                17.600000
0.469                17.658333
0.424                17.681818
0.428                17.692857
0.435                17.700000
0.395                17.775000
0.365                17.781818
0.407                17.790909
0.724                17.800000
0.691                17.800000
0.665                17.800000
0.366                17.814286
0.512                17.820000
0.542                17.840000
0.042                17.850000
0.387                17.869231
0.376                17.875000
0.466                17.880000
0.577                17.900000
0.043                17.914286
0.454                17.925000
0.401                17.938462
0.356                17.939286
0.323                17.951724
0.333                17.966667
0.565                17.983333
0.410                17.990000
0.770                18.000000
0.687                18.000000
0.566                18.000000
0.473                18.000000
0.372                18.000000
0.675                18.000000
0.497                18.020000
0.403                18.040000
0.304                18.044118
0.553                18.050000
0.364                18.070370
0.386                18.082353
0.448                18.100000
0.539                18.100000
0.529                18.100000
0.717                18.100000
0.357                18.104000
0.345                18.107692
0.476                18.120000
0.460                18.130769
0.342                18.140000
0.350                18.148387
0.369                18.150000
0.286                18.188095
0.411                18.230000
0.540                18.250000
0.569                18.250000
0.503                18.271429
0.437                18.283333
0.418                18.315385
0.047                18.316667
0.313                18.363889
0.321                18.387500
0.420                18.390909
0.564                18.400000
0.044                18.433333
0.274                18.450980
0.425                18.470000
0.363                18.473333
0.647                18.500000
0.404                18.512500
0.389                18.513333
0.413                18.536364
0.385                18.571429
0.293                18.573810
0.423                18.600000
0.685                18.600000
0.282                18.605882
0.275                18.611429
0.093                18.626042
0.104                18.632813
0.587                18.633333
0.319                18.642000
0.524                18.657143
0.355                18.658824
0.096                18.680717
0.378                18.687500
0.239                18.687692
0.336                18.687879
0.593                18.700000
0.619                18.700000
0.596                18.700000
0.289                18.717308
0.305                18.723077
0.373                18.738462
0.292                18.740816
0.434                18.760000
0.294                18.780952
0.361                18.782609
0.408                18.783333
0.374                18.785714
0.470                18.805556
0.287                18.825000
0.087                18.826154
0.422                18.833333
0.290                18.849057
0.328                18.850000
0.107                18.850000
0.362                18.852174
0.368                18.853846
0.327                18.860714
0.246                18.867692
0.101                18.868526
0.370                18.873684
0.379                18.885714
0.316                18.885714
0.354                18.891304
0.280                18.905882
0.281                18.909434
0.534                18.925000
0.079                18.931884
0.441                18.933333
0.095                18.946694
0.077                18.950667
0.301                18.957500
0.254                18.968966
0.348                18.977778
0.314                18.978125
0.244                18.982258
0.256                18.982353
0.284                18.986047
0.283                18.987805
0.068                18.988636
0.267                18.992424
0.106                18.996484
0.429                19.000000
0.740                19.000000
0.677                19.000000
0.623                19.000000
0.638                19.000000
0.307                19.002632
0.309                19.013514
0.351                19.016667
0.444                19.016667
0.360                19.022581
0.337                19.023810
0.085                19.026437
0.440                19.029412
0.273                19.030435
0.276                19.030909
0.464                19.033333
0.089                19.041709
0.331                19.042424
0.074                19.043411
0.091                19.044762
0.472                19.050000
0.097                19.068304
0.247                19.068657
0.099                19.071233
0.217                19.080682
0.263                19.081159
0.109                19.081949
0.258                19.084615
0.118                19.086192
0.312                19.086667
0.298                19.089796
0.296                19.091176
0.618                19.100000
0.226                19.109375
0.324                19.126471
0.081                19.127545
0.086                19.127723
0.291                19.132609
0.262                19.134921
0.073                19.140000
0.082                19.145143
0.083                19.152147
0.332                19.172727
0.359                19.187500
0.092                19.195982
0.453                19.200000
0.585                19.200000
0.306                19.200000
0.517                19.200000
0.108                19.209200
0.325                19.213636
0.478                19.225000
0.094                19.227586
0.261                19.229310
0.098                19.236364
0.105                19.238710
0.334                19.242857
0.335                19.244444
0.272                19.245833
0.128                19.250000
0.116                19.258824
0.119                19.263180
0.322                19.264103
0.088                19.266397
0.277                19.267568
0.129                19.268582
0.417                19.270000
0.232                19.286111
0.078                19.300588
0.264                19.306250
0.358                19.308000
0.343                19.311765
0.482                19.314286
0.259                19.316923
0.076                19.335526
0.153                19.338506
0.237                19.343529
0.390                19.344000
0.457                19.357143
0.075                19.362069
0.102                19.367500
0.409                19.372727
0.430                19.375000
0.505                19.375000
0.228                19.393805
0.084                19.406098
0.133                19.406584
0.115                19.411027
0.131                19.412033
0.221                19.412150
0.103                19.412295
0.231                19.414085
0.213                19.414286
0.111                19.415289
0.480                19.416667
0.175                19.439779
0.397                19.441667
0.052                19.457143
0.205                19.485586
0.257                19.486567
0.235                19.491304
0.113                19.493392
0.346                19.496154
0.310                19.500000
0.631                19.500000
0.488                19.500000
0.127                19.502713
0.297                19.512963
0.122                19.523077
0.288                19.523684
0.243                19.526230
0.182                19.528289
0.121                19.544891
0.069                19.545192
0.238                19.552083
0.202                19.552593
0.117                19.561304
0.199                19.563043
0.172                19.570718
0.211                19.583465
0.271                19.587755
0.242                19.590909
0.347                19.594737
0.380                19.595833
0.066                19.603750
0.245                19.613889
0.212                19.614159
0.399                19.614286
0.049                19.616667
0.145                19.627027
0.124                19.629167
0.126                19.631868
0.326                19.637931
0.353                19.638889
0.144                19.639189
0.137                19.640476
0.251                19.641791
0.154                19.645455
0.215                19.649541
0.188                19.668794
0.367                19.685000
0.194                19.689147
0.320                19.689362
0.112                19.691165
0.139                19.693171
0.383                19.700000
0.308                19.703030
0.174                19.704142
0.173                19.707643
0.266                19.715000
0.241                19.717284
0.167                19.721891
0.193                19.730328
0.450                19.730769
0.220                19.733036
0.427                19.733333
0.341                19.733333
0.371                19.738889
0.059                19.739130
0.303                19.743590
0.352                19.747826
0.159                19.748529
0.340                19.748571
0.196                19.748667
0.224                19.757447
0.181                19.766901
0.146                19.768545
0.053                19.770588
0.216                19.780000
0.132                19.781313
0.165                19.783041
0.143                19.784651
0.198                19.804762
0.189                19.806329
0.204                19.809322
0.065                19.809722
0.311                19.810000
0.163                19.814793
0.248                19.818750
0.156                19.819340
0.402                19.823077
0.339                19.823077
0.168                19.823404
0.148                19.825248
0.222                19.827957
0.253                19.834783
0.279                19.840541
0.114                19.847414
0.125                19.862651
0.151                19.862996
0.171                19.865000
0.072                19.875258
0.048                19.880000
0.123                19.881532
0.071                19.885827
0.234                19.886076
0.149                19.891710
0.388                19.892308
0.039                19.900000
0.035                19.900000
0.038                19.900000
0.531                19.900000
0.479                19.900000
0.138                19.909292
0.317                19.911628
0.155                19.912565
0.062                19.915686
0.142                19.927103
0.190                19.940782
0.161                19.942162
0.483                19.950000
0.270                19.951948
0.186                19.952593
0.382                19.953333
0.219                19.955000
0.185                19.973099
0.141                19.975217
0.152                19.980978
0.164                19.985238
0.162                19.990588
0.191                19.992517
0.063                19.997826
0.252                20.002439
0.299                20.004878
0.338                20.007143
0.229                20.013514
0.439                20.014286
0.302                20.025000
0.147                20.029717
0.255                20.031579
0.100                20.035363
0.192                20.035556
0.136                20.035931
0.218                20.045000
0.214                20.053043
0.135                20.057490
0.451                20.060000
0.207                20.062500
0.249                20.063380
0.208                20.064356
0.064                20.070000
0.233                20.071134
0.187                20.071640
0.201                20.079000
0.315                20.081818
0.285                20.090476
0.166                20.094595
0.269                20.095000
0.170                20.095305
0.260                20.095890
0.046                20.100000
0.195                20.100862
0.176                20.101333
0.329                20.118519
0.134                20.122318
0.223                20.126804
0.300                20.128947
0.489                20.140000
0.375                20.141667
0.067                20.150000
0.330                20.162500
0.157                20.166845
0.278                20.169841
0.477                20.175000
0.061                20.179487
0.295                20.179545
0.432                20.181250
0.130                20.183596
0.110                20.185577
0.398                20.188889
0.184                20.189091
0.177                20.191463
0.240                20.197872
0.030                20.207438
0.197                20.211667
0.183                20.212791
0.349                20.224000
0.500                20.225000
0.230                20.233028
0.178                20.234286
0.400                20.238889
0.209                20.241071
0.180                20.251852
0.140                20.252685
0.377                20.280000
0.200                20.291515
0.169                20.296951
0.158                20.301064
0.150                20.325714
0.203                20.325962
0.265                20.334043
0.225                20.336634
0.160                20.372065
0.080                20.380952
0.236                20.382278
0.268                20.388679
0.210                20.400633
0.179                20.418590
0.120                20.419943
0.041                20.433333
0.090                20.436547
0.433                20.437500
0.250                20.448980
0.414                20.466667
0.513                20.466667
0.318                20.475000
0.057                20.477419
0.206                20.521930
0.227                20.523437
0.056                20.581481
0.058                20.592105
0.040                20.600645
0.443                20.633333
0.547                20.650000
0.468                20.650000
0.051                20.655556
0.070                20.669620
0.392                20.723077
0.630                20.766667
0.506                20.900000
0.060                20.909953
0.050                20.962222
0.025                21.000000
0.055                21.003571
0.499                21.040000
0.603                21.050000
0.421                21.080000
0.525                21.100000
0.020                21.108197
0.054                21.175000
0.018                21.433333
0.520                21.491667
0.431                21.625000
0.023                21.700000
0.550                21.720000
0.610                21.800000
0.650                21.900000
0.026                21.900000
0.010                21.950000
0.016                22.200000
0.490                22.414286
0.590                22.500000
0.458                22.550000
0.426                22.566667
0.008                22.600000
0.651                22.600000
0.704                22.700000
0.600                22.950000
0.560                22.966667
0.495                23.350000
0.021                23.400000
0.000                23.604802
0.019                23.800000
0.028                23.800000
0.015                24.472727
0.014                24.721739
0.017                24.920000
0.031                25.350000
0.013                25.428571
0.034                29.200000
0.580                      NaN
0.620                      NaN
0.680                      NaN
0.690                      NaN
0.700                      NaN
0.720                      NaN
0.750                      NaN
0.760                      NaN

In [100]:
#Wave Height to Turbidity
with pd.option_context('display.max_rows', None):
    print(df.groupby('Wave Height')[['Turbidity']].mean().sort_values(by='Turbidity'))

              Turbidity
Wave Height
0.028          0.000000
0.034          0.000000
0.575          0.000000
0.025          0.000000
0.545          0.000000
0.016          0.000000
0.583          0.000000
0.576          0.000000
0.017          0.018000
0.018          0.023333
0.021          0.025000
0.014          0.044348
0.019          0.050000
0.015          0.130909
0.013          0.135714
0.038          0.230000
0.035          0.250000
0.039          0.290000
0.041          0.333333
0.042          0.350000
0.045          0.470000
0.043          0.512857
0.044          0.516667
0.008          0.520000
0.046          0.522000
0.048          0.600000
1.229          0.600000
0.052          0.660714
0.051          0.674444
0.049          0.728333
0.047          0.755000
0.000          0.909463
0.055          0.926429
0.058          0.961053
0.061          0.973846
0.059          1.018478
0.054          1.021875
0.057          1.071290
0.064          1.098125
0.102          1.194167
0.063          1.216087
0.065          1.232778
0.053          1.248235
0.098          1.249727
0.085          1.356609
0.093          1.366146
0.095          1.372686
0.067          1.376757
0.072          1.377010
0.083          1.414663
0.092          1.437366
0.087          1.456667
0.089          1.492563
0.091          1.498095
0.079          1.524638
0.073          1.592400
0.148          1.609158
0.076          1.653618
0.097          1.681429
0.141          1.693913
0.106          1.694727
0.031          1.725000
0.135          1.733644
0.164          1.736286
0.101          1.754701
0.126          1.762564
0.119          1.807364
0.026          1.810000
0.145          1.810180
0.074          1.836279
0.099          1.840639
0.125          1.851285
0.157          1.865241
0.094          1.884871
0.096          1.895067
0.071          1.906142
0.056          1.911852
0.115          1.913042
0.023          1.920000
0.068          1.957386
0.078          1.980588
0.082          1.985657
0.109          2.000361
0.123          2.003694
0.507          2.010000
0.086          2.038020
0.144          2.047477
0.105          2.082437
0.136          2.126667
0.132          2.130202
0.111          2.133347
0.146          2.134789
0.084          2.167195
0.143          2.167349
0.129          2.201686
0.137          2.203048
0.124          2.205833
0.131          2.209585
0.159          2.210294
0.127          2.233876
0.149          2.243161
0.227          2.254063
0.228          2.266726
0.104          2.296797
0.167          2.307662
0.222          2.308280
0.107          2.316304
0.153          2.318563
0.118          2.342134
0.154          2.342139
0.158          2.429521
0.244          2.443548
0.139          2.507171
0.112          2.509518
0.152          2.510815
0.114          2.525733
0.219          2.532200
0.075          2.533862
0.117          2.535435
0.156          2.550943
0.183          2.565988
0.088          2.576883
0.163          2.581420
0.113          2.632026
0.242          2.645606
0.168          2.651277
0.223          2.714124
0.166          2.792108
0.133          2.808807
0.187          2.820501
0.066          2.850000
0.128          2.857826
0.062          2.862941
0.122          2.894060
0.236          2.909114
0.229          2.909324
0.174          2.918284
0.175          2.953978
0.245          2.958333
0.155          2.963298
0.488          2.965000
0.399          2.985714
0.235          3.047101
0.162          3.061824
0.171          3.079500
0.161          3.091676
0.271          3.097959
0.325          3.126818
0.169          3.135976
0.332          3.171818
0.165          3.367778
0.305          3.372051
0.268          3.384151
0.224          3.396170
0.208          3.468911
0.375          3.494167
0.323          3.498966
0.387          3.510769
0.334          3.529643
0.304          3.550294
0.292          3.552653
0.286          3.579524
0.263          3.597391
0.234          3.644810
0.246          3.647692
0.314          3.660000
0.121          3.663686
0.147          3.665991
0.255          3.674386
0.207          3.681696
0.184          3.718727
0.177          3.747927
0.218          3.761300
0.265          3.793404
0.247          3.793433
0.151          3.812247
0.138          3.843496
0.388          3.853077
0.252          3.894390
0.259          3.899231
0.281          3.940000
0.342          4.000667
0.317          4.012093
0.277          4.037568
0.413          4.060909
0.423          4.063333
0.214          4.077391
0.359          4.078125
0.527          4.090000
0.238          4.102292
0.204          4.131864
0.233          4.141237
0.081          4.155629
0.315          4.164242
0.283          4.189756
0.272          4.195972
0.506          4.205000
0.345          4.234231
0.326          4.241724
0.442          4.260000
0.312          4.277000
0.256          4.292500
0.353          4.295000
0.398          4.334444
0.302          4.357500
0.077          4.375467
0.295          4.392273
0.296          4.403529
0.108          4.422480
0.221          4.473832
0.134          4.477167
0.282          4.498235
0.179          4.554231
0.346          4.641923
0.185          4.655731
0.240          4.677128
0.321          4.700625
0.495          4.710000
0.193          4.712787
0.289          4.715385
0.306          4.736585
0.069          4.757692
0.366          4.834286
0.251          4.839403
0.211          4.860079
0.116          4.894790
0.293          4.930714
0.303          4.934615
0.279          4.934865
0.421          5.044000
0.299          5.050244
0.361          5.143043
0.308          5.165758
0.178          5.198071
0.285          5.203333
0.298          5.239184
0.103          5.255820
0.329          5.309630
0.392          5.340769
0.170          5.358451
0.351          5.386000
0.213          5.445338
0.426          5.455556
0.250          5.532959
0.186          5.538667
0.704          5.560000
0.273          5.573043
0.383          5.590667
0.264          5.627500
0.339          5.664231
0.198          5.679603
0.257          5.713582
0.343          5.731176
0.424          5.745455
0.431          5.752500
0.324          5.828824
0.310          5.842600
0.363          5.881333
0.176          5.938600
0.262          5.941111
0.274          5.941765
0.330          5.983750
0.142          5.995327
0.439          6.020000
0.202          6.031185
0.357          6.034800
0.291          6.067174
0.215          6.110642
0.350          6.125161
0.382          6.138667
0.377          6.152667
0.269          6.184750
0.203          6.203846
0.356          6.277857
0.191          6.280544
0.276          6.294364
0.327          6.364643
0.173          6.457325
0.280          6.461176
0.160          6.471660
0.322          6.486154
0.630          6.520000
0.237          6.535529
0.130          6.563281
0.243          6.593934
0.226          6.609167
0.284          6.657209
0.217          6.658750
0.443          6.680000
0.248          6.684219
0.347          6.699474
0.449          6.756667
0.192          6.757926
0.335          6.760000
0.414          6.790000
0.651          6.870000
0.428          6.871429
0.258          6.888974
0.405          6.890000
0.337          6.907143
0.311          6.940750
0.365          7.216364
0.385          7.241429
0.220          7.272232
0.371          7.284444
0.531          7.285000
0.232          7.292222
0.320          7.426170
0.478          7.435000
0.200          7.466364
0.307          7.567895
0.352          7.625652
0.290          7.643585
0.140          7.701544
0.509          7.832000
0.386          7.845294
0.254          7.868276
0.364          7.966667
0.182          7.968816
0.525          7.970000
0.309          7.992703
0.402          8.032308
0.294          8.040238
0.210          8.198481
0.190          8.215978
0.446          8.218333
0.379          8.265238
0.120          8.266952
0.189          8.323797
0.181          8.400493
0.380          8.416667
0.333          8.426667
0.172          8.450387
0.358          8.530000
0.150          8.608163
0.520          8.632500
0.417          8.660000
0.355          8.700000
0.396          8.762500
0.349          8.762800
0.331          8.812121
0.300          8.983289
0.319          9.038600
0.241          9.043457
0.270          9.047403
0.180          9.064339
0.538          9.233333
0.340          9.260286
0.344          9.265217
0.374          9.317143
0.655          9.330000
0.505          9.360000
1.117          9.440000
0.472          9.463333
0.194          9.526357
0.605          9.565000
1.467          9.580000
0.408          9.602500
0.267          9.609848
0.369          9.625000
0.497          9.646000
0.196          9.848467
0.549          9.930000
0.110          9.938510
0.474          9.966000
0.230          9.982661
0.451         10.008000
0.297         10.038148
0.197         10.067500
0.458         10.280000
0.482         10.325714
0.496         10.380000
0.328         10.396944
0.400         10.428889
0.404         10.432500
0.212         10.498761
0.452         10.547500
0.479         10.566667
0.100         10.622998
0.433         10.652500
0.367         10.681000
0.201         10.757800
0.368         10.893077
0.390         10.954400
0.336         11.000606
0.288         11.020526
0.517         11.105000
0.316         11.115714
0.456         11.150000
0.409         11.160909
0.632         11.260000
0.406         11.421765
0.354         11.546087
0.384         11.841429
0.195         11.918362
0.249         11.934789
0.410         11.973000
0.411         11.978000
0.418         12.046154
0.481         12.120000
0.490         12.144286
0.461         12.150000
0.537         12.170000
0.523         12.225000
0.665         12.290000
0.407         12.309091
0.539         12.350000
0.503         12.387143
0.698         12.400000
0.397         12.415000
0.231         12.447887
0.513         12.460000
0.544         12.505000
0.206         12.510877
0.556         12.570000
0.560         12.648333
0.430         12.658750
0.403         12.804000
0.644         12.900000
0.373         12.957692
0.389         13.114667
0.489         13.182000
0.629         13.240000
0.391         13.244667
0.585         13.380000
0.445         13.471111
0.188         13.494823
0.599         13.495000
0.485         13.496667
0.589         13.560000
0.528         13.680000
0.438         13.754286
0.313         13.838889
0.441         13.907778
0.341         13.992222
0.499         14.068000
0.566         14.086667
0.512         14.212000
0.216         14.214100
0.593         14.320000
0.500         14.621875
0.427         14.684444
0.209         14.765536
0.460         14.786154
0.090         14.805942
0.381         14.955714
0.370         15.002105
0.429         15.047500
0.205         15.144234
0.577         15.170000
0.436         15.288750
0.473         15.316667
0.394         15.538667
0.360         15.684839
0.555         15.910000
0.450         15.978462
0.600         15.985000
0.457         16.077143
0.569         16.175000
0.432         16.335000
0.261         16.474310
0.434         16.580000
0.615         16.645000
0.199         16.687609
0.533         16.710000
0.540         16.900000
0.626         16.920000
0.253         17.012754
0.522         17.045000
0.239         17.156769
0.425         17.177000
0.467         17.295000
0.372         17.408000
0.444         17.458333
0.225         17.548119
0.080         17.557434
0.338         17.592500
0.596         17.640000
0.362         17.652174
0.440         17.708824
0.260         17.711370
0.477         17.832500
0.470         17.862778
0.468         17.870000
0.501         18.028000
0.463         18.126250
0.567         18.196667
0.595         18.410000
0.412         18.727500
0.542         18.748000
0.454         18.855000
0.466         19.020000
0.275         19.044000
0.647         19.090000
0.541         19.272500
0.070         19.306772
0.348         19.393333
0.462         19.903333
0.393         20.093750
0.401         20.373846
0.486         20.403333
0.526         20.426000
0.420         20.525000
0.524         20.778571
0.476         20.916000
0.455         21.033333
0.416         21.189167
0.435         21.305000
0.464         21.326667
0.623         21.390000
0.010         21.435000
0.770         21.490000
0.475         21.545000
0.287         21.653958
0.515         21.905000
0.543         22.164000
0.637         22.200000
0.607         22.236667
0.587         22.376667
0.628         22.440000
0.508         22.565000
0.510         22.627857
0.563         22.747500
0.553         22.760000
0.559         22.817500
0.604         22.950000
0.660         23.100000
0.552         23.490000
0.483         23.790000
0.550         23.821000
0.535         23.932000
0.565         24.651667
0.376         24.810000
0.618         25.100000
0.487         25.342222
0.465         25.350000
0.650         25.620000
0.469         25.640833
0.493         25.760000
0.301         25.801500
0.570         25.856667
0.266         26.082500
0.591         26.130000
0.060         26.554645
0.447         26.715000
0.437         26.816667
0.459         26.967500
0.631         27.080000
0.278         27.088413
0.554         27.106667
0.571         27.115000
0.378         27.399375
0.610         27.610000
0.422         27.846667
0.395         27.982500
0.611         28.180000
0.584         29.106000
0.603         29.280000
0.592         29.670000
0.050         30.105778
0.619         30.310000
0.453         30.458750
0.608         30.670000
0.498         30.870000
0.516         30.993333
0.020         31.193770
0.638         31.740000
0.687         31.770000
0.419         31.935714
0.561         31.962000
0.529         32.070000
0.574         32.140000
0.502         32.595000
0.040         32.775742
0.521         33.623333
0.415         33.911667
0.590         34.047500
0.675         34.190000
0.484         34.830000
0.318         34.898571
0.534         35.260000
0.492         35.596667
0.547         35.775000
0.518         35.796667
0.613         36.076667
0.030         36.539835
0.685         36.870000
0.658         38.270000
0.594         38.406667
0.625         39.580000
0.480         39.875000
0.602         40.310000
0.530         40.488000
0.558         42.152000
0.494         42.386667
0.514         43.236667
0.471         44.565000
0.691         44.900000
0.511         45.837500
0.562         45.952500
0.612         47.260000
0.491         49.012000
0.546         49.060000
0.504         49.940000
0.557         50.413333
0.597         50.970000
0.532         51.210000
0.717         53.140000
0.677         53.260000
0.740         53.260000
0.551         53.263333
0.606         58.637500
0.448         59.200000
0.601         60.700000
0.536         62.508000
0.519         65.987500
0.598         66.395000
0.640         75.380000
0.564         81.710000
0.724         83.670000
0.548        127.140000
0.580               NaN
0.620               NaN
0.680               NaN
0.690               NaN
0.700               NaN
0.720               NaN
0.750               NaN
0.760               NaN